### ISSUE TITLE
Issue-chore: Add Google integration support to user profile

### ISSUE THREAD

**Issue by satokihanada** [satokihanada/nexusai#17]
Automated Review Comments
Issues in packages/api/nodemon.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in packages/api/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in packages/api/src/lib/google.auth.ts:
  - (2, 'Hardcoded string found')
Issues in packages/api/src/prisma/schema.prisma:
  - (68, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
Issues in packages/api/src/services/auth.service.ts:
  - (2, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (141, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
