### ISSUE TITLE
Issue-chore: Add Google OAuth support

### ISSUE THREAD

**Issue by satokihanada** [satokihanada/nexusai#19]
Automated Review Comments
Issues in packages/api/src/config/env.ts:
  - (3, 'Hardcoded string found')
Issues in packages/api/src/controller/user.controller.ts:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
Issues in packages/api/src/lib/google.auth.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in packages/api/src/prisma/schema.prisma:
  - (16, 'Hardcoded string found')
Issues in packages/api/src/routes/auth.route.ts:
  - (15, 'Line exceeds 80 characters')
Issues in packages/api/src/services/auth.service.ts:
  - (21, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (88, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
