### ISSUE TITLE
Issue-chore: Add Google OAuth support and integrate with user profile

### ISSUE THREAD

**Issue by satokihanada** [satokihanada/nexusai#21]
Automated Review Comments
Issues in packages/api/src/middlewares/auth.ts:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
Issues in packages/api/src/routes/user.route.ts:
  - (1, 'Hardcoded string found')
Issues in packages/api/src/services/auth.service.ts:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (66, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
